### ISSUE TITLE
Key listing at /keys/<user> is broken

### ISSUE THREAD

**Issue by u1f408** [videogame-hacker/ssh-lockbox#4]
This is the same bug as #2 - a missing `.values()` on the retrieval from the database [at list_keys.py:11](https://github.com/half-cambodian-hacker-man/ssh-lockbox/blob/main/lockbox/routes/list_keys.py#L11), resulting in this:

```
[iris@miku ~]$ curl -s https://lockbox.redacted.domain/keys/iris
key_algorithm key_contents
```

It's probably worth going over all the database accesses and double-checking for this?

**Comment by char** [comment]
Are you using SQLite, or something else? It's working fine for me with SQLite.

My keys are here: https://keys.hackery.site/keys/half-kh-hacker

**Comment by char** [comment]
A database query through encode's `databases` using aiosqlite just gives me a big tuple, which is why the destructuring works for me:

```shell
$ python3 -m asyncio
>>> from lockbox.db import keys, database
>>> await database.fetch_all(keys.select())
[(1, 1, 'ssh-ed25519', 'AAAAC3NzaC1lZDI1NTE5AAAAIIU+VqeTeS+zm1j55fjrBbQtnxPmpYR1PHH4AWkKgjUM', 'half-kh-hacker@hackery-desktop'), ...
```

edit: Looks like this is an artifact of https://github.com/encode/databases/issues/214 . I assumed it would be already unified.

**Comment by char** [comment]
Okay, it looks like you can get regular RowProxy objects out while using PostgreSQL by using the `aiopg` backend instead of the `postgres` one. I think this is an upstream `encode/databases` issue.

**Comment by u1f408** [comment]
Confirming that using `aiopg` has the expected behavior, so this does appear to be an upstream bug. Thanks for pointing that out!

**Comment by char** [comment]
Okay, I've removed the (redundant) `values()` calls, and I'll document that one should use the `aiopg` backend for PostgreSQL support.
